# DO NOT EDIT THIS FILE!
#
# Python module Extended_CF generated by omniidl

import omniORB
omniORB.updateModule("sca.cf.Extended_CF")

# ** 1. Stub files contributing to this module
import sca.cf.UTCTime_idl
import sca.cf.DeviceComponent_idl

# ** 2. Sub-modules

# ** 3. End
