// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CF_hh__
#define __CF_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CF
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CF
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CF
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <CFCommonTypes.h>
#endif
#ifndef __CFFile_hh_EXTERNAL_GUARD__
#define __CFFile_hh_EXTERNAL_GUARD__
#include <CFFile.h>
#endif
#ifndef __CFFileSystem_hh_EXTERNAL_GUARD__
#define __CFFileSystem_hh_EXTERNAL_GUARD__
#include <CFFileSystem.h>
#endif
#ifndef __CFPlatformTypes_hh_EXTERNAL_GUARD__
#define __CFPlatformTypes_hh_EXTERNAL_GUARD__
#include <CFPlatformTypes.h>
#endif
#ifndef __CFSpecializedInfo_hh_EXTERNAL_GUARD__
#define __CFSpecializedInfo_hh_EXTERNAL_GUARD__
#include <CFSpecializedInfo.h>
#endif
#ifndef __CFComponentIdentifier_hh_EXTERNAL_GUARD__
#define __CFComponentIdentifier_hh_EXTERNAL_GUARD__
#include <CFComponentIdentifier.h>
#endif
#ifndef __CFControllableInterface_hh_EXTERNAL_GUARD__
#define __CFControllableInterface_hh_EXTERNAL_GUARD__
#include <CFControllableInterface.h>
#endif
#ifndef __CFLifeCycle_hh_EXTERNAL_GUARD__
#define __CFLifeCycle_hh_EXTERNAL_GUARD__
#include <CFLifeCycle.h>
#endif
#ifndef __CFPortAccessor_hh_EXTERNAL_GUARD__
#define __CFPortAccessor_hh_EXTERNAL_GUARD__
#include <CFPortAccessor.h>
#endif
#ifndef __CFPropertySet_hh_EXTERNAL_GUARD__
#define __CFPropertySet_hh_EXTERNAL_GUARD__
#include <CFPropertySet.h>
#endif
#ifndef __CFTestableInterface_hh_EXTERNAL_GUARD__
#define __CFTestableInterface_hh_EXTERNAL_GUARD__
#include <CFTestableInterface.h>
#endif
#ifndef __CFAggregateDevice_hh_EXTERNAL_GUARD__
#define __CFAggregateDevice_hh_EXTERNAL_GUARD__
#include <CFAggregateDevice.h>
#endif
#ifndef __CFCapacityManagement_hh_EXTERNAL_GUARD__
#define __CFCapacityManagement_hh_EXTERNAL_GUARD__
#include <CFCapacityManagement.h>
#endif
#ifndef __CFDeviceAttributes_hh_EXTERNAL_GUARD__
#define __CFDeviceAttributes_hh_EXTERNAL_GUARD__
#include <CFDeviceAttributes.h>
#endif
#ifndef __CFExecutableInterface_hh_EXTERNAL_GUARD__
#define __CFExecutableInterface_hh_EXTERNAL_GUARD__
#include <CFExecutableInterface.h>
#endif
#ifndef __CFLoadableInterface_hh_EXTERNAL_GUARD__
#define __CFLoadableInterface_hh_EXTERNAL_GUARD__
#include <CFLoadableInterface.h>
#endif
#ifndef __CFAdministratableInterface_hh_EXTERNAL_GUARD__
#define __CFAdministratableInterface_hh_EXTERNAL_GUARD__
#include <CFAdministratableInterface.h>
#endif
#ifndef __CFApplicationManager_hh_EXTERNAL_GUARD__
#define __CFApplicationManager_hh_EXTERNAL_GUARD__
#include <CFApplicationManager.h>
#endif
#ifndef __CFDeploymentAttributes_hh_EXTERNAL_GUARD__
#define __CFDeploymentAttributes_hh_EXTERNAL_GUARD__
#include <CFDeploymentAttributes.h>
#endif
#ifndef __CFApplicationFactory_hh_EXTERNAL_GUARD__
#define __CFApplicationFactory_hh_EXTERNAL_GUARD__
#include <CFApplicationFactory.h>
#endif
#ifndef __CFComponentRegistry_hh_EXTERNAL_GUARD__
#define __CFComponentRegistry_hh_EXTERNAL_GUARD__
#include <CFComponentRegistry.h>
#endif
#ifndef __CFDomainInstallation_hh_EXTERNAL_GUARD__
#define __CFDomainInstallation_hh_EXTERNAL_GUARD__
#include <CFDomainInstallation.h>
#endif
#ifndef __CFFileManager_hh_EXTERNAL_GUARD__
#define __CFFileManager_hh_EXTERNAL_GUARD__
#include <CFFileManager.h>
#endif
#ifndef __CFDomainManager_hh_EXTERNAL_GUARD__
#define __CFDomainManager_hh_EXTERNAL_GUARD__
#include <CFDomainManager.h>
#endif
#ifndef __CFEventChannelRegistry_hh_EXTERNAL_GUARD__
#define __CFEventChannelRegistry_hh_EXTERNAL_GUARD__
#include <CFEventChannelRegistry.h>
#endif
#ifndef __CFReleasableManager_hh_EXTERNAL_GUARD__
#define __CFReleasableManager_hh_EXTERNAL_GUARD__
#include <CFReleasableManager.h>
#endif
#ifndef __CFComponentFactory_hh_EXTERNAL_GUARD__
#define __CFComponentFactory_hh_EXTERNAL_GUARD__
#include <CFComponentFactory.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif











#undef _core_attr
#undef _dyn_attr





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CF
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CF
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CF
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CF
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CF
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CF
#endif

#endif  // __CF_hh__

