// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFAdministratableInterface_hh__
#define __CFAdministratableInterface_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mAdministratableInterface__
#define __CF_mAdministratableInterface__
  class AdministratableInterface;
  class _objref_AdministratableInterface;
  class _impl_AdministratableInterface;
  
  typedef _objref_AdministratableInterface* AdministratableInterface_ptr;
  typedef AdministratableInterface_ptr AdministratableInterfaceRef;

  class AdministratableInterface_Helper {
  public:
    typedef AdministratableInterface_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_AdministratableInterface, AdministratableInterface_Helper> AdministratableInterface_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_AdministratableInterface,AdministratableInterface_Helper > AdministratableInterface_out;

#endif

  // interface AdministratableInterface
  class AdministratableInterface {
  public:
    // Declarations for this interface type.
    typedef AdministratableInterface_ptr _ptr_type;
    typedef AdministratableInterface_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    enum AdminType { LOCKED, SHUTTING_DOWN, UNLOCKED /*, __max_AdminType=0xffffffff */ };
    typedef AdminType& AdminType_out;

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_AdminType;

  
  };

  class _objref_AdministratableInterface :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    AdministratableInterface::AdminType adminState();
    void adminState(::CF::AdministratableInterface::AdminType _v);

    // Constructors
    inline _objref_AdministratableInterface()  { _PR_setobj(0); }  // nil
    _objref_AdministratableInterface(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_AdministratableInterface();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_AdministratableInterface(const _objref_AdministratableInterface&);
    _objref_AdministratableInterface& operator = (const _objref_AdministratableInterface&);
    // not implemented

    friend class AdministratableInterface;
  };

  class _pof_AdministratableInterface : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_AdministratableInterface() : _OMNI_NS(proxyObjectFactory)(AdministratableInterface::_PD_repoId) {}
    virtual ~_pof_AdministratableInterface();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_AdministratableInterface :
    public virtual omniServant
  {
  public:
    virtual ~_impl_AdministratableInterface();

    virtual AdministratableInterface::AdminType adminState() = 0;
    virtual void adminState(::CF::AdministratableInterface::AdminType _v) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_AdministratableInterface;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class AdministratableInterface :
    public virtual CF::_impl_AdministratableInterface,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~AdministratableInterface();

    inline ::CF::AdministratableInterface_ptr _this() {
      return (::CF::AdministratableInterface_ptr) _do_this(::CF::AdministratableInterface::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(CF::AdministratableInterface::AdminType _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (CF::AdministratableInterface::AdminType& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= CF::AdministratableInterface::UNLOCKED) {
    _e = (CF::AdministratableInterface::AdminType) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}

void operator<<=(::CORBA::Any& _a, CF::AdministratableInterface::AdminType _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::AdministratableInterface::AdminType& _s);

void operator<<=(::CORBA::Any& _a, CF::AdministratableInterface_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::AdministratableInterface_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::AdministratableInterface_ptr& _s);



inline void
CF::AdministratableInterface::_marshalObjRef(::CF::AdministratableInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFAdministratableInterface
#endif

#endif  // __CFAdministratableInterface_hh__

