// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFBooleanSeq_hh__
#define __CFBooleanSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_BooleanSeq;

  class BooleanSeq_var;

  class BooleanSeq : public _CORBA_Unbounded_Sequence_Boolean {
  public:
    typedef BooleanSeq_var _var_type;
    inline BooleanSeq() {}
    inline BooleanSeq(const BooleanSeq& _s)
      : _CORBA_Unbounded_Sequence_Boolean(_s) {}

    inline BooleanSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_Boolean(_max) {}
    inline BooleanSeq(_CORBA_ULong _max, _CORBA_ULong _len, BooleanType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_Boolean(_max, _len, _val, _rel) {}

  

    inline BooleanSeq& operator = (const BooleanSeq& _s) {
      _CORBA_Unbounded_Sequence_Boolean::operator=(_s);
      return *this;
    }
  };

  class BooleanSeq_out;

  class BooleanSeq_var {
  public:
    inline BooleanSeq_var() : _pd_seq(0) {}
    inline BooleanSeq_var(BooleanSeq* _s) : _pd_seq(_s) {}
    inline BooleanSeq_var(const BooleanSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new BooleanSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~BooleanSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline BooleanSeq_var& operator = (BooleanSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline BooleanSeq_var& operator = (const BooleanSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new BooleanSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline BooleanType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline BooleanSeq* operator -> () { return _pd_seq; }
    inline const BooleanSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator BooleanSeq& () const { return *_pd_seq; }
#else
    inline operator const BooleanSeq& () const { return *_pd_seq; }
    inline operator BooleanSeq& () { return *_pd_seq; }
#endif
      
    inline const BooleanSeq& in() const { return *_pd_seq; }
    inline BooleanSeq&       inout()    { return *_pd_seq; }
    inline BooleanSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline BooleanSeq* _retn() { BooleanSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class BooleanSeq_out;
    
  private:
    BooleanSeq* _pd_seq;
  };

  class BooleanSeq_out {
  public:
    inline BooleanSeq_out(BooleanSeq*& _s) : _data(_s) { _data = 0; }
    inline BooleanSeq_out(BooleanSeq_var& _s)
      : _data(_s._pd_seq) { _s = (BooleanSeq*) 0; }
    inline BooleanSeq_out(const BooleanSeq_out& _s) : _data(_s._data) {}
    inline BooleanSeq_out& operator = (const BooleanSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline BooleanSeq_out& operator = (BooleanSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator BooleanSeq*&()  { return _data; }
    inline BooleanSeq*& ptr()       { return _data; }
    inline BooleanSeq* operator->() { return _data; }

    inline BooleanType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    BooleanSeq*& _data;

  private:
    BooleanSeq_out();
    BooleanSeq_out& operator=(const BooleanSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::BooleanSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::BooleanSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::BooleanSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::BooleanSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFBooleanSeq
#endif

#endif  // __CFBooleanSeq_hh__

