// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFCapacityManagement_hh__
#define __CFCapacityManagement_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif



#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif
#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <CFCommonTypes.h>
#endif
#ifndef __CFPlatformTypes_hh_EXTERNAL_GUARD__
#define __CFPlatformTypes_hh_EXTERNAL_GUARD__
#include <CFPlatformTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mCapacityManagement__
#define __CF_mCapacityManagement__
  class CapacityManagement;
  class _objref_CapacityManagement;
  class _impl_CapacityManagement;
  
  typedef _objref_CapacityManagement* CapacityManagement_ptr;
  typedef CapacityManagement_ptr CapacityManagementRef;

  class CapacityManagement_Helper {
  public:
    typedef CapacityManagement_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_CapacityManagement, CapacityManagement_Helper> CapacityManagement_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_CapacityManagement,CapacityManagement_Helper > CapacityManagement_out;

#endif

  // interface CapacityManagement
  class CapacityManagement {
  public:
    // Declarations for this interface type.
    typedef CapacityManagement_ptr _ptr_type;
    typedef CapacityManagement_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    enum UsageType { IDLE, ACTIVE, BUSY /*, __max_UsageType=0xffffffff */ };
    typedef UsageType& UsageType_out;

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_UsageType;

    class InvalidCapacity : public ::CORBA::UserException {
    public:
      
      ::CORBA::String_member msg;

      Properties capacities;

    

      inline InvalidCapacity() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidCapacity(const InvalidCapacity&);
      InvalidCapacity(const char* i_msg, const Properties i_capacities);
      InvalidCapacity& operator=(const InvalidCapacity&);
      virtual ~InvalidCapacity();
      virtual void _raise() const;
      static InvalidCapacity* _downcast(::CORBA::Exception*);
      static const InvalidCapacity* _downcast(const ::CORBA::Exception*);
      static inline InvalidCapacity* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidCapacity;

  
  };

  class _objref_CapacityManagement :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    CapacityManagement::UsageType usageState();
    ::CORBA::Boolean allocateCapacity(const ::CF::Properties& capacities);
    void deallocateCapacity(const ::CF::Properties& capacities);

    // Constructors
    inline _objref_CapacityManagement()  { _PR_setobj(0); }  // nil
    _objref_CapacityManagement(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_CapacityManagement();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_CapacityManagement(const _objref_CapacityManagement&);
    _objref_CapacityManagement& operator = (const _objref_CapacityManagement&);
    // not implemented

    friend class CapacityManagement;
  };

  class _pof_CapacityManagement : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_CapacityManagement() : _OMNI_NS(proxyObjectFactory)(CapacityManagement::_PD_repoId) {}
    virtual ~_pof_CapacityManagement();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_CapacityManagement :
    public virtual omniServant
  {
  public:
    virtual ~_impl_CapacityManagement();

    virtual CapacityManagement::UsageType usageState() = 0;
    virtual ::CORBA::Boolean allocateCapacity(const ::CF::Properties& capacities) = 0;
    virtual void deallocateCapacity(const ::CF::Properties& capacities) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_CapacityManagement;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class CapacityManagement :
    public virtual CF::_impl_CapacityManagement,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~CapacityManagement();

    inline ::CF::CapacityManagement_ptr _this() {
      return (::CF::CapacityManagement_ptr) _do_this(::CF::CapacityManagement::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(CF::CapacityManagement::UsageType _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (CF::CapacityManagement::UsageType& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= CF::CapacityManagement::BUSY) {
    _e = (CF::CapacityManagement::UsageType) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}

void operator<<=(::CORBA::Any& _a, CF::CapacityManagement::UsageType _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::CapacityManagement::UsageType& _s);

void operator<<=(::CORBA::Any& _a, const CF::CapacityManagement::InvalidCapacity& _s);
void operator<<=(::CORBA::Any& _a, const CF::CapacityManagement::InvalidCapacity* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::CapacityManagement::InvalidCapacity*& _sp);

void operator<<=(::CORBA::Any& _a, CF::CapacityManagement_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::CapacityManagement_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::CapacityManagement_ptr& _s);



inline void
CF::CapacityManagement::_marshalObjRef(::CF::CapacityManagement_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCapacityManagement
#endif

#endif  // __CFCapacityManagement_hh__

