// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFCharSeq_hh__
#define __CFCharSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_CharSeq;

  class CharSeq_var;

  class CharSeq : public _CORBA_Unbounded_Sequence_Char {
  public:
    typedef CharSeq_var _var_type;
    inline CharSeq() {}
    inline CharSeq(const CharSeq& _s)
      : _CORBA_Unbounded_Sequence_Char(_s) {}

    inline CharSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_Char(_max) {}
    inline CharSeq(_CORBA_ULong _max, _CORBA_ULong _len, CharType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_Char(_max, _len, _val, _rel) {}

  

    inline CharSeq& operator = (const CharSeq& _s) {
      _CORBA_Unbounded_Sequence_Char::operator=(_s);
      return *this;
    }
  };

  class CharSeq_out;

  class CharSeq_var {
  public:
    inline CharSeq_var() : _pd_seq(0) {}
    inline CharSeq_var(CharSeq* _s) : _pd_seq(_s) {}
    inline CharSeq_var(const CharSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new CharSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~CharSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline CharSeq_var& operator = (CharSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline CharSeq_var& operator = (const CharSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new CharSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline CharType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline CharSeq* operator -> () { return _pd_seq; }
    inline const CharSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator CharSeq& () const { return *_pd_seq; }
#else
    inline operator const CharSeq& () const { return *_pd_seq; }
    inline operator CharSeq& () { return *_pd_seq; }
#endif
      
    inline const CharSeq& in() const { return *_pd_seq; }
    inline CharSeq&       inout()    { return *_pd_seq; }
    inline CharSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline CharSeq* _retn() { CharSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class CharSeq_out;
    
  private:
    CharSeq* _pd_seq;
  };

  class CharSeq_out {
  public:
    inline CharSeq_out(CharSeq*& _s) : _data(_s) { _data = 0; }
    inline CharSeq_out(CharSeq_var& _s)
      : _data(_s._pd_seq) { _s = (CharSeq*) 0; }
    inline CharSeq_out(const CharSeq_out& _s) : _data(_s._data) {}
    inline CharSeq_out& operator = (const CharSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline CharSeq_out& operator = (CharSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator CharSeq*&()  { return _data; }
    inline CharSeq*& ptr()       { return _data; }
    inline CharSeq* operator->() { return _data; }

    inline CharType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    CharSeq*& _data;

  private:
    CharSeq_out();
    CharSeq_out& operator=(const CharSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::CharSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::CharSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::CharSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::CharSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFCharSeq
#endif

#endif  // __CFCharSeq_hh__

