// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFControllableInterface_hh__
#define __CFControllableInterface_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <CFCommonTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mControllableInterface__
#define __CF_mControllableInterface__
  class ControllableInterface;
  class _objref_ControllableInterface;
  class _impl_ControllableInterface;
  
  typedef _objref_ControllableInterface* ControllableInterface_ptr;
  typedef ControllableInterface_ptr ControllableInterfaceRef;

  class ControllableInterface_Helper {
  public:
    typedef ControllableInterface_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ControllableInterface, ControllableInterface_Helper> ControllableInterface_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ControllableInterface,ControllableInterface_Helper > ControllableInterface_out;

#endif

  // interface ControllableInterface
  class ControllableInterface {
  public:
    // Declarations for this interface type.
    typedef ControllableInterface_ptr _ptr_type;
    typedef ControllableInterface_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class StartError : public ::CORBA::UserException {
    public:
      
      ErrorNumberType errorNumber;

      ::CORBA::String_member msg;

    

      inline StartError() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      StartError(const StartError&);
      StartError(ErrorNumberType i_errorNumber, const char* i_msg);
      StartError& operator=(const StartError&);
      virtual ~StartError();
      virtual void _raise() const;
      static StartError* _downcast(::CORBA::Exception*);
      static const StartError* _downcast(const ::CORBA::Exception*);
      static inline StartError* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_StartError;

    class StopError : public ::CORBA::UserException {
    public:
      
      ErrorNumberType errorNumber;

      ::CORBA::String_member msg;

    

      inline StopError() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      StopError(const StopError&);
      StopError(ErrorNumberType i_errorNumber, const char* i_msg);
      StopError& operator=(const StopError&);
      virtual ~StopError();
      virtual void _raise() const;
      static StopError* _downcast(::CORBA::Exception*);
      static const StopError* _downcast(const ::CORBA::Exception*);
      static inline StopError* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_StopError;

  
  };

  class _objref_ControllableInterface :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Boolean started();
    void start();
    void stop();

    // Constructors
    inline _objref_ControllableInterface()  { _PR_setobj(0); }  // nil
    _objref_ControllableInterface(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ControllableInterface();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ControllableInterface(const _objref_ControllableInterface&);
    _objref_ControllableInterface& operator = (const _objref_ControllableInterface&);
    // not implemented

    friend class ControllableInterface;
  };

  class _pof_ControllableInterface : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ControllableInterface() : _OMNI_NS(proxyObjectFactory)(ControllableInterface::_PD_repoId) {}
    virtual ~_pof_ControllableInterface();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ControllableInterface :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ControllableInterface();

    virtual ::CORBA::Boolean started() = 0;
    virtual void start() = 0;
    virtual void stop() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ControllableInterface;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class ControllableInterface :
    public virtual CF::_impl_ControllableInterface,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ControllableInterface();

    inline ::CF::ControllableInterface_ptr _this() {
      return (::CF::ControllableInterface_ptr) _do_this(::CF::ControllableInterface::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::ControllableInterface::StartError& _s);
void operator<<=(::CORBA::Any& _a, const CF::ControllableInterface::StartError* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ControllableInterface::StartError*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::ControllableInterface::StopError& _s);
void operator<<=(::CORBA::Any& _a, const CF::ControllableInterface::StopError* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ControllableInterface::StopError*& _sp);

void operator<<=(::CORBA::Any& _a, CF::ControllableInterface_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::ControllableInterface_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ControllableInterface_ptr& _s);



inline void
CF::ControllableInterface::_marshalObjRef(::CF::ControllableInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFControllableInterface
#endif

#endif  // __CFControllableInterface_hh__

