// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFExecutableInterface_hh__
#define __CFExecutableInterface_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <CFCommonTypes.h>
#endif
#ifndef __CFPlatformTypes_hh_EXTERNAL_GUARD__
#define __CFPlatformTypes_hh_EXTERNAL_GUARD__
#include <CFPlatformTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mExecutableInterface__
#define __CF_mExecutableInterface__
  class ExecutableInterface;
  class _objref_ExecutableInterface;
  class _impl_ExecutableInterface;
  
  typedef _objref_ExecutableInterface* ExecutableInterface_ptr;
  typedef ExecutableInterface_ptr ExecutableInterfaceRef;

  class ExecutableInterface_Helper {
  public:
    typedef ExecutableInterface_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ExecutableInterface, ExecutableInterface_Helper> ExecutableInterface_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ExecutableInterface,ExecutableInterface_Helper > ExecutableInterface_out;

#endif

  // interface ExecutableInterface
  class ExecutableInterface {
  public:
    // Declarations for this interface type.
    typedef ExecutableInterface_ptr _ptr_type;
    typedef ExecutableInterface_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class InvalidProcess : public ::CORBA::UserException {
    public:
      
      ErrorNumberType errorNumber;

      ::CORBA::String_member msg;

    

      inline InvalidProcess() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidProcess(const InvalidProcess&);
      InvalidProcess(ErrorNumberType i_errorNumber, const char* i_msg);
      InvalidProcess& operator=(const InvalidProcess&);
      virtual ~InvalidProcess();
      virtual void _raise() const;
      static InvalidProcess* _downcast(::CORBA::Exception*);
      static const InvalidProcess* _downcast(const ::CORBA::Exception*);
      static inline InvalidProcess* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidProcess;

    class InvalidFunction : public ::CORBA::UserException {
    public:
      
      

      inline InvalidFunction() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidFunction(const InvalidFunction&);
      
      InvalidFunction& operator=(const InvalidFunction&);
      virtual ~InvalidFunction();
      virtual void _raise() const;
      static InvalidFunction* _downcast(::CORBA::Exception*);
      static const InvalidFunction* _downcast(const ::CORBA::Exception*);
      static inline InvalidFunction* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      inline void operator>>=(cdrStream&) const { }
      inline void operator<<=(cdrStream&) { }

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidFunction;

    struct ExecutionID_Type {
      typedef _CORBA_ConstrType_Variable_Var<ExecutionID_Type> _var_type;

      
      ::CORBA::ULongLong threadId;

      ::CORBA::ULongLong processId;

      ::CORBA::String_member processCollocation;

      ULongSeq cores;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef ExecutionID_Type::_var_type ExecutionID_Type_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< ExecutionID_Type,ExecutionID_Type_var > ExecutionID_Type_out;

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_ExecutionID_Type;

    class InvalidParameters : public ::CORBA::UserException {
    public:
      
      Properties invalidParms;

    

      inline InvalidParameters() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidParameters(const InvalidParameters&);
      InvalidParameters(const Properties i_invalidParms);
      InvalidParameters& operator=(const InvalidParameters&);
      virtual ~InvalidParameters();
      virtual void _raise() const;
      static InvalidParameters* _downcast(::CORBA::Exception*);
      static const InvalidParameters* _downcast(const ::CORBA::Exception*);
      static inline InvalidParameters* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidParameters;

    class InvalidOptions : public ::CORBA::UserException {
    public:
      
      Properties invalidOpts;

    

      inline InvalidOptions() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidOptions(const InvalidOptions&);
      InvalidOptions(const Properties i_invalidOpts);
      InvalidOptions& operator=(const InvalidOptions&);
      virtual ~InvalidOptions();
      virtual void _raise() const;
      static InvalidOptions* _downcast(::CORBA::Exception*);
      static const InvalidOptions* _downcast(const ::CORBA::Exception*);
      static inline InvalidOptions* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidOptions;

    static _core_attr const char * STACK_SIZE_ID;

    static _core_attr const char * PRIORITY_ID;

    static _core_attr const char * EXEC_DEVICE_PROCESS_SPACE;

    static _core_attr const char * PROCESS_COLLOCATION_ID;

    static _core_attr const char * ENTRY_POINT_ID;

    static _core_attr const char * CORE_AFFINITY_ID;

    class ExecuteFail : public ::CORBA::UserException {
    public:
      
      ErrorNumberType errorNumber;

      ::CORBA::String_member msg;

    

      inline ExecuteFail() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      ExecuteFail(const ExecuteFail&);
      ExecuteFail(ErrorNumberType i_errorNumber, const char* i_msg);
      ExecuteFail& operator=(const ExecuteFail&);
      virtual ~ExecuteFail();
      virtual void _raise() const;
      static ExecuteFail* _downcast(::CORBA::Exception*);
      static const ExecuteFail* _downcast(const ::CORBA::Exception*);
      static inline ExecuteFail* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_ExecuteFail;

  
  };

  class _objref_ExecutableInterface :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void terminate(const ::CF::ExecutableInterface::ExecutionID_Type& executionId);
    ExecutableInterface::ExecutionID_Type* execute(const char* filename, const ::CF::Properties& options, const ::CF::Properties& parameters);

    // Constructors
    inline _objref_ExecutableInterface()  { _PR_setobj(0); }  // nil
    _objref_ExecutableInterface(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ExecutableInterface();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ExecutableInterface(const _objref_ExecutableInterface&);
    _objref_ExecutableInterface& operator = (const _objref_ExecutableInterface&);
    // not implemented

    friend class ExecutableInterface;
  };

  class _pof_ExecutableInterface : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ExecutableInterface() : _OMNI_NS(proxyObjectFactory)(ExecutableInterface::_PD_repoId) {}
    virtual ~_pof_ExecutableInterface();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ExecutableInterface :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ExecutableInterface();

    virtual void terminate(const ::CF::ExecutableInterface::ExecutionID_Type& executionId) = 0;
    virtual ExecutableInterface::ExecutionID_Type* execute(const char* filename, const ::CF::Properties& options, const ::CF::Properties& parameters) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ExecutableInterface;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class ExecutableInterface :
    public virtual CF::_impl_ExecutableInterface,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ExecutableInterface();

    inline ::CF::ExecutableInterface_ptr _this() {
      return (::CF::ExecutableInterface_ptr) _do_this(::CF::ExecutableInterface::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidProcess& _s);
void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidProcess* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::InvalidProcess*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidFunction& _s);
void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidFunction* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::InvalidFunction*& _sp);

extern void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::ExecutionID_Type& _s);
extern void operator<<=(::CORBA::Any& _a, CF::ExecutableInterface::ExecutionID_Type* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ExecutableInterface::ExecutionID_Type*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::ExecutionID_Type*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidParameters& _s);
void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidParameters* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::InvalidParameters*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidOptions& _s);
void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::InvalidOptions* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::InvalidOptions*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::ExecuteFail& _s);
void operator<<=(::CORBA::Any& _a, const CF::ExecutableInterface::ExecuteFail* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ExecutableInterface::ExecuteFail*& _sp);

void operator<<=(::CORBA::Any& _a, CF::ExecutableInterface_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::ExecutableInterface_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ExecutableInterface_ptr& _s);



inline void
CF::ExecutableInterface::_marshalObjRef(::CF::ExecutableInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFExecutableInterface
#endif

#endif  // __CFExecutableInterface_hh__

