// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFLifeCycle_hh__
#define __CFLifeCycle_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <CFCommonTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mLifeCycle__
#define __CF_mLifeCycle__
  class LifeCycle;
  class _objref_LifeCycle;
  class _impl_LifeCycle;
  
  typedef _objref_LifeCycle* LifeCycle_ptr;
  typedef LifeCycle_ptr LifeCycleRef;

  class LifeCycle_Helper {
  public:
    typedef LifeCycle_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_LifeCycle, LifeCycle_Helper> LifeCycle_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_LifeCycle,LifeCycle_Helper > LifeCycle_out;

#endif

  // interface LifeCycle
  class LifeCycle {
  public:
    // Declarations for this interface type.
    typedef LifeCycle_ptr _ptr_type;
    typedef LifeCycle_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class InitializeError : public ::CORBA::UserException {
    public:
      
      StringSequence errorMessages;

    

      inline InitializeError() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InitializeError(const InitializeError&);
      InitializeError(const StringSequence i_errorMessages);
      InitializeError& operator=(const InitializeError&);
      virtual ~InitializeError();
      virtual void _raise() const;
      static InitializeError* _downcast(::CORBA::Exception*);
      static const InitializeError* _downcast(const ::CORBA::Exception*);
      static inline InitializeError* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InitializeError;

    class ReleaseError : public ::CORBA::UserException {
    public:
      
      StringSequence errorMessages;

    

      inline ReleaseError() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      ReleaseError(const ReleaseError&);
      ReleaseError(const StringSequence i_errorMessages);
      ReleaseError& operator=(const ReleaseError&);
      virtual ~ReleaseError();
      virtual void _raise() const;
      static ReleaseError* _downcast(::CORBA::Exception*);
      static const ReleaseError* _downcast(const ::CORBA::Exception*);
      static inline ReleaseError* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_ReleaseError;

  
  };

  class _objref_LifeCycle :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void initialize();
    void releaseObject();

    // Constructors
    inline _objref_LifeCycle()  { _PR_setobj(0); }  // nil
    _objref_LifeCycle(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_LifeCycle();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_LifeCycle(const _objref_LifeCycle&);
    _objref_LifeCycle& operator = (const _objref_LifeCycle&);
    // not implemented

    friend class LifeCycle;
  };

  class _pof_LifeCycle : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_LifeCycle() : _OMNI_NS(proxyObjectFactory)(LifeCycle::_PD_repoId) {}
    virtual ~_pof_LifeCycle();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_LifeCycle :
    public virtual omniServant
  {
  public:
    virtual ~_impl_LifeCycle();

    virtual void initialize() = 0;
    virtual void releaseObject() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_LifeCycle;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class LifeCycle :
    public virtual CF::_impl_LifeCycle,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~LifeCycle();

    inline ::CF::LifeCycle_ptr _this() {
      return (::CF::LifeCycle_ptr) _do_this(::CF::LifeCycle::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::LifeCycle::InitializeError& _s);
void operator<<=(::CORBA::Any& _a, const CF::LifeCycle::InitializeError* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::LifeCycle::InitializeError*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::LifeCycle::ReleaseError& _s);
void operator<<=(::CORBA::Any& _a, const CF::LifeCycle::ReleaseError* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::LifeCycle::ReleaseError*& _sp);

void operator<<=(::CORBA::Any& _a, CF::LifeCycle_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::LifeCycle_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::LifeCycle_ptr& _s);



inline void
CF::LifeCycle::_marshalObjRef(::CF::LifeCycle_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLifeCycle
#endif

#endif  // __CFLifeCycle_hh__

