// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFLongSeq_hh__
#define __CFLongSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_LongSeq;

  class LongSeq_var;

  class LongSeq : public _CORBA_Unbounded_Sequence_w_FixSizeElement< LongType, 4, 4 >  {
  public:
    typedef LongSeq_var _var_type;
    inline LongSeq() {}
    inline LongSeq(const LongSeq& _s)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< LongType, 4, 4 > (_s) {}

    inline LongSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< LongType, 4, 4 > (_max) {}
    inline LongSeq(_CORBA_ULong _max, _CORBA_ULong _len, LongType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< LongType, 4, 4 > (_max, _len, _val, _rel) {}

  

    inline LongSeq& operator = (const LongSeq& _s) {
      _CORBA_Unbounded_Sequence_w_FixSizeElement< LongType, 4, 4 > ::operator=(_s);
      return *this;
    }
  };

  class LongSeq_out;

  class LongSeq_var {
  public:
    inline LongSeq_var() : _pd_seq(0) {}
    inline LongSeq_var(LongSeq* _s) : _pd_seq(_s) {}
    inline LongSeq_var(const LongSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new LongSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~LongSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline LongSeq_var& operator = (LongSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline LongSeq_var& operator = (const LongSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new LongSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline LongType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline LongSeq* operator -> () { return _pd_seq; }
    inline const LongSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator LongSeq& () const { return *_pd_seq; }
#else
    inline operator const LongSeq& () const { return *_pd_seq; }
    inline operator LongSeq& () { return *_pd_seq; }
#endif
      
    inline const LongSeq& in() const { return *_pd_seq; }
    inline LongSeq&       inout()    { return *_pd_seq; }
    inline LongSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline LongSeq* _retn() { LongSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class LongSeq_out;
    
  private:
    LongSeq* _pd_seq;
  };

  class LongSeq_out {
  public:
    inline LongSeq_out(LongSeq*& _s) : _data(_s) { _data = 0; }
    inline LongSeq_out(LongSeq_var& _s)
      : _data(_s._pd_seq) { _s = (LongSeq*) 0; }
    inline LongSeq_out(const LongSeq_out& _s) : _data(_s._data) {}
    inline LongSeq_out& operator = (const LongSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline LongSeq_out& operator = (LongSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator LongSeq*&()  { return _data; }
    inline LongSeq*& ptr()       { return _data; }
    inline LongSeq* operator->() { return _data; }

    inline LongType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    LongSeq*& _data;

  private:
    LongSeq_out();
    LongSeq_out& operator=(const LongSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::LongSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::LongSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::LongSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::LongSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFLongSeq
#endif

#endif  // __CFLongSeq_hh__

