// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFPropertySet_hh__
#define __CFPropertySet_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif



#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mPropertySet__
#define __CF_mPropertySet__
  class PropertySet;
  class _objref_PropertySet;
  class _impl_PropertySet;
  
  typedef _objref_PropertySet* PropertySet_ptr;
  typedef PropertySet_ptr PropertySetRef;

  class PropertySet_Helper {
  public:
    typedef PropertySet_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_PropertySet, PropertySet_Helper> PropertySet_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_PropertySet,PropertySet_Helper > PropertySet_out;

#endif

  // interface PropertySet
  class PropertySet {
  public:
    // Declarations for this interface type.
    typedef PropertySet_ptr _ptr_type;
    typedef PropertySet_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class InvalidConfiguration : public ::CORBA::UserException {
    public:
      
      ::CORBA::String_member msg;

      Properties invalidProperties;

    

      inline InvalidConfiguration() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      InvalidConfiguration(const InvalidConfiguration&);
      InvalidConfiguration(const char* i_msg, const Properties i_invalidProperties);
      InvalidConfiguration& operator=(const InvalidConfiguration&);
      virtual ~InvalidConfiguration();
      virtual void _raise() const;
      static InvalidConfiguration* _downcast(::CORBA::Exception*);
      static const InvalidConfiguration* _downcast(const ::CORBA::Exception*);
      static inline InvalidConfiguration* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_InvalidConfiguration;

    class PartialConfiguration : public ::CORBA::UserException {
    public:
      
      Properties invalidProperties;

    

      inline PartialConfiguration() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      PartialConfiguration(const PartialConfiguration&);
      PartialConfiguration(const Properties i_invalidProperties);
      PartialConfiguration& operator=(const PartialConfiguration&);
      virtual ~PartialConfiguration();
      virtual void _raise() const;
      static PartialConfiguration* _downcast(::CORBA::Exception*);
      static const PartialConfiguration* _downcast(const ::CORBA::Exception*);
      static inline PartialConfiguration* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_PartialConfiguration;

  
  };

  class _objref_PropertySet :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void configure(const ::CF::Properties& configProperties);
    void query(::CF::Properties& configProperties);

    // Constructors
    inline _objref_PropertySet()  { _PR_setobj(0); }  // nil
    _objref_PropertySet(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_PropertySet();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_PropertySet(const _objref_PropertySet&);
    _objref_PropertySet& operator = (const _objref_PropertySet&);
    // not implemented

    friend class PropertySet;
  };

  class _pof_PropertySet : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_PropertySet() : _OMNI_NS(proxyObjectFactory)(PropertySet::_PD_repoId) {}
    virtual ~_pof_PropertySet();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_PropertySet :
    public virtual omniServant
  {
  public:
    virtual ~_impl_PropertySet();

    virtual void configure(const ::CF::Properties& configProperties) = 0;
    virtual void query(::CF::Properties& configProperties) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_PropertySet;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class PropertySet :
    public virtual CF::_impl_PropertySet,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~PropertySet();

    inline ::CF::PropertySet_ptr _this() {
      return (::CF::PropertySet_ptr) _do_this(::CF::PropertySet::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::PropertySet::InvalidConfiguration& _s);
void operator<<=(::CORBA::Any& _a, const CF::PropertySet::InvalidConfiguration* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::PropertySet::InvalidConfiguration*& _sp);

void operator<<=(::CORBA::Any& _a, const CF::PropertySet::PartialConfiguration& _s);
void operator<<=(::CORBA::Any& _a, const CF::PropertySet::PartialConfiguration* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::PropertySet::PartialConfiguration*& _sp);

void operator<<=(::CORBA::Any& _a, CF::PropertySet_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::PropertySet_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::PropertySet_ptr& _s);



inline void
CF::PropertySet::_marshalObjRef(::CF::PropertySet_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFPropertySet
#endif

#endif  // __CFPropertySet_hh__

