// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFReleasableManager_hh__
#define __CFReleasableManager_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mReleasableManager__
#define __CF_mReleasableManager__
  class ReleasableManager;
  class _objref_ReleasableManager;
  class _impl_ReleasableManager;
  
  typedef _objref_ReleasableManager* ReleasableManager_ptr;
  typedef ReleasableManager_ptr ReleasableManagerRef;

  class ReleasableManager_Helper {
  public:
    typedef ReleasableManager_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ReleasableManager, ReleasableManager_Helper> ReleasableManager_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ReleasableManager,ReleasableManager_Helper > ReleasableManager_out;

#endif

  // interface ReleasableManager
  class ReleasableManager {
  public:
    // Declarations for this interface type.
    typedef ReleasableManager_ptr _ptr_type;
    typedef ReleasableManager_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ReleasableManager :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void shutdown();

    // Constructors
    inline _objref_ReleasableManager()  { _PR_setobj(0); }  // nil
    _objref_ReleasableManager(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ReleasableManager();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ReleasableManager(const _objref_ReleasableManager&);
    _objref_ReleasableManager& operator = (const _objref_ReleasableManager&);
    // not implemented

    friend class ReleasableManager;
  };

  class _pof_ReleasableManager : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ReleasableManager() : _OMNI_NS(proxyObjectFactory)(ReleasableManager::_PD_repoId) {}
    virtual ~_pof_ReleasableManager();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ReleasableManager :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ReleasableManager();

    virtual void shutdown() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ReleasableManager;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class ReleasableManager :
    public virtual CF::_impl_ReleasableManager,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ReleasableManager();

    inline ::CF::ReleasableManager_ptr _this() {
      return (::CF::ReleasableManager_ptr) _do_this(::CF::ReleasableManager::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, CF::ReleasableManager_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::ReleasableManager_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ReleasableManager_ptr& _s);



inline void
CF::ReleasableManager::_marshalObjRef(::CF::ReleasableManager_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFReleasableManager
#endif

#endif  // __CFReleasableManager_hh__

