// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFShortSeq_hh__
#define __CFShortSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ShortSeq;

  class ShortSeq_var;

  class ShortSeq : public _CORBA_Unbounded_Sequence_w_FixSizeElement< ShortType, 2, 2 >  {
  public:
    typedef ShortSeq_var _var_type;
    inline ShortSeq() {}
    inline ShortSeq(const ShortSeq& _s)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ShortType, 2, 2 > (_s) {}

    inline ShortSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ShortType, 2, 2 > (_max) {}
    inline ShortSeq(_CORBA_ULong _max, _CORBA_ULong _len, ShortType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ShortType, 2, 2 > (_max, _len, _val, _rel) {}

  

    inline ShortSeq& operator = (const ShortSeq& _s) {
      _CORBA_Unbounded_Sequence_w_FixSizeElement< ShortType, 2, 2 > ::operator=(_s);
      return *this;
    }
  };

  class ShortSeq_out;

  class ShortSeq_var {
  public:
    inline ShortSeq_var() : _pd_seq(0) {}
    inline ShortSeq_var(ShortSeq* _s) : _pd_seq(_s) {}
    inline ShortSeq_var(const ShortSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ShortSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ShortSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ShortSeq_var& operator = (ShortSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ShortSeq_var& operator = (const ShortSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new ShortSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline ShortType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ShortSeq* operator -> () { return _pd_seq; }
    inline const ShortSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ShortSeq& () const { return *_pd_seq; }
#else
    inline operator const ShortSeq& () const { return *_pd_seq; }
    inline operator ShortSeq& () { return *_pd_seq; }
#endif
      
    inline const ShortSeq& in() const { return *_pd_seq; }
    inline ShortSeq&       inout()    { return *_pd_seq; }
    inline ShortSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ShortSeq* _retn() { ShortSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ShortSeq_out;
    
  private:
    ShortSeq* _pd_seq;
  };

  class ShortSeq_out {
  public:
    inline ShortSeq_out(ShortSeq*& _s) : _data(_s) { _data = 0; }
    inline ShortSeq_out(ShortSeq_var& _s)
      : _data(_s._pd_seq) { _s = (ShortSeq*) 0; }
    inline ShortSeq_out(const ShortSeq_out& _s) : _data(_s._data) {}
    inline ShortSeq_out& operator = (const ShortSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ShortSeq_out& operator = (ShortSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator ShortSeq*&()  { return _data; }
    inline ShortSeq*& ptr()       { return _data; }
    inline ShortSeq* operator->() { return _data; }

    inline ShortType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ShortSeq*& _data;

  private:
    ShortSeq_out();
    ShortSeq_out& operator=(const ShortSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::ShortSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::ShortSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ShortSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ShortSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFShortSeq
#endif

#endif  // __CFShortSeq_hh__

