// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFTestableInterface_hh__
#define __CFTestableInterface_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif



#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <CFProperties.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

#ifndef __CF_mTestableInterface__
#define __CF_mTestableInterface__
  class TestableInterface;
  class _objref_TestableInterface;
  class _impl_TestableInterface;
  
  typedef _objref_TestableInterface* TestableInterface_ptr;
  typedef TestableInterface_ptr TestableInterfaceRef;

  class TestableInterface_Helper {
  public:
    typedef TestableInterface_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_TestableInterface, TestableInterface_Helper> TestableInterface_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_TestableInterface,TestableInterface_Helper > TestableInterface_out;

#endif

  // interface TestableInterface
  class TestableInterface {
  public:
    // Declarations for this interface type.
    typedef TestableInterface_ptr _ptr_type;
    typedef TestableInterface_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    class UnknownTest : public ::CORBA::UserException {
    public:
      
      

      inline UnknownTest() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      UnknownTest(const UnknownTest&);
      
      UnknownTest& operator=(const UnknownTest&);
      virtual ~UnknownTest();
      virtual void _raise() const;
      static UnknownTest* _downcast(::CORBA::Exception*);
      static const UnknownTest* _downcast(const ::CORBA::Exception*);
      static inline UnknownTest* _narrow(::CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      inline void operator>>=(cdrStream&) const { }
      inline void operator<<=(cdrStream&) { }

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual ::CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_UnknownTest;

  
  };

  class _objref_TestableInterface :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void runTest(::CORBA::ULong testid, ::CF::Properties& testValues);

    // Constructors
    inline _objref_TestableInterface()  { _PR_setobj(0); }  // nil
    _objref_TestableInterface(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_TestableInterface();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_TestableInterface(const _objref_TestableInterface&);
    _objref_TestableInterface& operator = (const _objref_TestableInterface&);
    // not implemented

    friend class TestableInterface;
  };

  class _pof_TestableInterface : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_TestableInterface() : _OMNI_NS(proxyObjectFactory)(TestableInterface::_PD_repoId) {}
    virtual ~_pof_TestableInterface();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_TestableInterface :
    public virtual omniServant
  {
  public:
    virtual ~_impl_TestableInterface();

    virtual void runTest(::CORBA::ULong testid, ::CF::Properties& testValues) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_TestableInterface;

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

  class TestableInterface :
    public virtual CF::_impl_TestableInterface,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~TestableInterface();

    inline ::CF::TestableInterface_ptr _this() {
      return (::CF::TestableInterface_ptr) _do_this(::CF::TestableInterface::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::TestableInterface::UnknownTest& _s);
void operator<<=(::CORBA::Any& _a, const CF::TestableInterface::UnknownTest* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::TestableInterface::UnknownTest*& _sp);

void operator<<=(::CORBA::Any& _a, CF::TestableInterface_ptr _s);
void operator<<=(::CORBA::Any& _a, CF::TestableInterface_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::TestableInterface_ptr& _s);



inline void
CF::TestableInterface::_marshalObjRef(::CF::TestableInterface_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFTestableInterface
#endif

#endif  // __CFTestableInterface_hh__

