// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFULongLongSeq_hh__
#define __CFULongLongSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ULongLongSeq;

  class ULongLongSeq_var;

  class ULongLongSeq : public _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongLongType, 8, 8 >  {
  public:
    typedef ULongLongSeq_var _var_type;
    inline ULongLongSeq() {}
    inline ULongLongSeq(const ULongLongSeq& _s)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongLongType, 8, 8 > (_s) {}

    inline ULongLongSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongLongType, 8, 8 > (_max) {}
    inline ULongLongSeq(_CORBA_ULong _max, _CORBA_ULong _len, ULongLongType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongLongType, 8, 8 > (_max, _len, _val, _rel) {}

  

    inline ULongLongSeq& operator = (const ULongLongSeq& _s) {
      _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongLongType, 8, 8 > ::operator=(_s);
      return *this;
    }
  };

  class ULongLongSeq_out;

  class ULongLongSeq_var {
  public:
    inline ULongLongSeq_var() : _pd_seq(0) {}
    inline ULongLongSeq_var(ULongLongSeq* _s) : _pd_seq(_s) {}
    inline ULongLongSeq_var(const ULongLongSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ULongLongSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ULongLongSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ULongLongSeq_var& operator = (ULongLongSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ULongLongSeq_var& operator = (const ULongLongSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new ULongLongSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline ULongLongType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ULongLongSeq* operator -> () { return _pd_seq; }
    inline const ULongLongSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ULongLongSeq& () const { return *_pd_seq; }
#else
    inline operator const ULongLongSeq& () const { return *_pd_seq; }
    inline operator ULongLongSeq& () { return *_pd_seq; }
#endif
      
    inline const ULongLongSeq& in() const { return *_pd_seq; }
    inline ULongLongSeq&       inout()    { return *_pd_seq; }
    inline ULongLongSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ULongLongSeq* _retn() { ULongLongSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ULongLongSeq_out;
    
  private:
    ULongLongSeq* _pd_seq;
  };

  class ULongLongSeq_out {
  public:
    inline ULongLongSeq_out(ULongLongSeq*& _s) : _data(_s) { _data = 0; }
    inline ULongLongSeq_out(ULongLongSeq_var& _s)
      : _data(_s._pd_seq) { _s = (ULongLongSeq*) 0; }
    inline ULongLongSeq_out(const ULongLongSeq_out& _s) : _data(_s._data) {}
    inline ULongLongSeq_out& operator = (const ULongLongSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ULongLongSeq_out& operator = (ULongLongSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator ULongLongSeq*&()  { return _data; }
    inline ULongLongSeq*& ptr()       { return _data; }
    inline ULongLongSeq* operator->() { return _data; }

    inline ULongLongType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ULongLongSeq*& _data;

  private:
    ULongLongSeq_out();
    ULongLongSeq_out& operator=(const ULongLongSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::ULongLongSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::ULongLongSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ULongLongSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ULongLongSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongLongSeq
#endif

#endif  // __CFULongLongSeq_hh__

