// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __CFULongSeq_hh__
#define __CFULongSeq_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif



#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CF

_CORBA_MODULE_BEG

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ULongSeq;

  class ULongSeq_var;

  class ULongSeq : public _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongType, 4, 4 >  {
  public:
    typedef ULongSeq_var _var_type;
    inline ULongSeq() {}
    inline ULongSeq(const ULongSeq& _s)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongType, 4, 4 > (_s) {}

    inline ULongSeq(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongType, 4, 4 > (_max) {}
    inline ULongSeq(_CORBA_ULong _max, _CORBA_ULong _len, ULongType* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongType, 4, 4 > (_max, _len, _val, _rel) {}

  

    inline ULongSeq& operator = (const ULongSeq& _s) {
      _CORBA_Unbounded_Sequence_w_FixSizeElement< ULongType, 4, 4 > ::operator=(_s);
      return *this;
    }
  };

  class ULongSeq_out;

  class ULongSeq_var {
  public:
    inline ULongSeq_var() : _pd_seq(0) {}
    inline ULongSeq_var(ULongSeq* _s) : _pd_seq(_s) {}
    inline ULongSeq_var(const ULongSeq_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ULongSeq(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ULongSeq_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ULongSeq_var& operator = (ULongSeq* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ULongSeq_var& operator = (const ULongSeq_var& _s) {
      if (_s._pd_seq) {
        if (!_pd_seq)  _pd_seq = new ULongSeq;
        *_pd_seq = *_s._pd_seq;
      } else if (_pd_seq) {
        delete _pd_seq;
        _pd_seq = 0;
      }
      return *this;
    }
    inline ULongType& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ULongSeq* operator -> () { return _pd_seq; }
    inline const ULongSeq* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ULongSeq& () const { return *_pd_seq; }
#else
    inline operator const ULongSeq& () const { return *_pd_seq; }
    inline operator ULongSeq& () { return *_pd_seq; }
#endif
      
    inline const ULongSeq& in() const { return *_pd_seq; }
    inline ULongSeq&       inout()    { return *_pd_seq; }
    inline ULongSeq*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ULongSeq* _retn() { ULongSeq* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ULongSeq_out;
    
  private:
    ULongSeq* _pd_seq;
  };

  class ULongSeq_out {
  public:
    inline ULongSeq_out(ULongSeq*& _s) : _data(_s) { _data = 0; }
    inline ULongSeq_out(ULongSeq_var& _s)
      : _data(_s._pd_seq) { _s = (ULongSeq*) 0; }
    inline ULongSeq_out(const ULongSeq_out& _s) : _data(_s._data) {}
    inline ULongSeq_out& operator = (const ULongSeq_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ULongSeq_out& operator = (ULongSeq* _s) {
      _data = _s;
      return *this;
    }
    inline operator ULongSeq*&()  { return _data; }
    inline ULongSeq*& ptr()       { return _data; }
    inline ULongSeq* operator->() { return _data; }

    inline ULongType& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ULongSeq*& _data;

  private:
    ULongSeq_out();
    ULongSeq_out& operator=(const ULongSeq_var&);
  };

_CORBA_MODULE_END



_CORBA_MODULE POA_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_CF
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const CF::ULongSeq& _s);
void operator<<=(::CORBA::Any& _a, CF::ULongSeq* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, CF::ULongSeq*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const CF::ULongSeq*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CFULongSeq
#endif

#endif  // __CFULongSeq_hh__

