// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __bio__dataUshort_hh__
#define __bio__dataUshort_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif



#ifndef __CFProperties_hh_EXTERNAL_GUARD__
#define __CFProperties_hh_EXTERNAL_GUARD__
#include <sca/CF/CFProperties.h>
#endif
#ifndef __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#define __CFPrimitiveTypes_hh_EXTERNAL_GUARD__
#include <CFPrimitiveTypes.h>
#endif
#ifndef __CFULongLongSeq_hh_EXTERNAL_GUARD__
#define __CFULongLongSeq_hh_EXTERNAL_GUARD__
#include <CFULongLongSeq.h>
#endif
#ifndef __CFBooleanSeq_hh_EXTERNAL_GUARD__
#define __CFBooleanSeq_hh_EXTERNAL_GUARD__
#include <CFBooleanSeq.h>
#endif
#ifndef __CFULongSeq_hh_EXTERNAL_GUARD__
#define __CFULongSeq_hh_EXTERNAL_GUARD__
#include <CFULongSeq.h>
#endif
#ifndef __CFLongLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongLongSeq.h>
#endif
#ifndef __CFCharSeq_hh_EXTERNAL_GUARD__
#define __CFCharSeq_hh_EXTERNAL_GUARD__
#include <CFCharSeq.h>
#endif
#ifndef __CFUShortSeq_hh_EXTERNAL_GUARD__
#define __CFUShortSeq_hh_EXTERNAL_GUARD__
#include <CFUShortSeq.h>
#endif
#ifndef __CFLongSeq_hh_EXTERNAL_GUARD__
#define __CFLongSeq_hh_EXTERNAL_GUARD__
#include <CFLongSeq.h>
#endif
#ifndef __CFDoubleSeq_hh_EXTERNAL_GUARD__
#define __CFDoubleSeq_hh_EXTERNAL_GUARD__
#include <CFDoubleSeq.h>
#endif
#ifndef __CFShortSeq_hh_EXTERNAL_GUARD__
#define __CFShortSeq_hh_EXTERNAL_GUARD__
#include <CFShortSeq.h>
#endif
#ifndef __CFFloatSeq_hh_EXTERNAL_GUARD__
#define __CFFloatSeq_hh_EXTERNAL_GUARD__
#include <CFFloatSeq.h>
#endif
#ifndef __CFOctetSeq_hh_EXTERNAL_GUARD__
#define __CFOctetSeq_hh_EXTERNAL_GUARD__
#include <CFOctetSeq.h>
#endif
#ifndef __CFStringSeq_hh_EXTERNAL_GUARD__
#define __CFStringSeq_hh_EXTERNAL_GUARD__
#include <CFStringSeq.h>
#endif
#ifndef __CFCommonTypes_hh_EXTERNAL_GUARD__
#define __CFCommonTypes_hh_EXTERNAL_GUARD__
#include <sca/CF/CFCommonTypes.h>
#endif
#ifndef __Port_hh_EXTERNAL_GUARD__
#define __Port_hh_EXTERNAL_GUARD__
#include <sca/CF/Port.h>
#endif
#ifndef __QueryablePort_hh_EXTERNAL_GUARD__
#define __QueryablePort_hh_EXTERNAL_GUARD__
#include <sca/CF/QueryablePort.h>
#endif
#ifndef __AdditionalTypes_hh_EXTERNAL_GUARD__
#define __AdditionalTypes_hh_EXTERNAL_GUARD__
#include <sca/CF/AdditionalTypes.h>
#endif
#ifndef __bulkioDataTypes_hh_EXTERNAL_GUARD__
#define __bulkioDataTypes_hh_EXTERNAL_GUARD__
#include <sca/BULKIO/bulkioDataTypes.h>
#endif
#ifndef __bio__runtimeStats_hh_EXTERNAL_GUARD__
#define __bio__runtimeStats_hh_EXTERNAL_GUARD__
#include <sca/BULKIO/bio_runtimeStats.h>
#endif
#ifndef __bio__updateSRI_hh_EXTERNAL_GUARD__
#define __bio__updateSRI_hh_EXTERNAL_GUARD__
#include <sca/BULKIO/bio_updateSRI.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE BULKIO

_CORBA_MODULE_BEG

#ifndef __BULKIO_mdataUshort__
#define __BULKIO_mdataUshort__
  class dataUshort;
  class _objref_dataUshort;
  class _impl_dataUshort;
  
  typedef _objref_dataUshort* dataUshort_ptr;
  typedef dataUshort_ptr dataUshortRef;

  class dataUshort_Helper {
  public:
    typedef dataUshort_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_dataUshort, dataUshort_Helper> dataUshort_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_dataUshort,dataUshort_Helper > dataUshort_out;

#endif

  // interface dataUshort
  class dataUshort {
  public:
    // Declarations for this interface type.
    typedef dataUshort_ptr _ptr_type;
    typedef dataUshort_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_dataUshort :
    public virtual _objref_ProvidesPortStatisticsProvider,
    public virtual _objref_updateSRI
  {
  public:
    // IDL operations
    void pushPacket(const ::PortTypes::UshortSequence& data, const ::BULKIO::PrecisionUTCTime& T, ::CORBA::Boolean EOS, const char* streamID);

    // Constructors
    inline _objref_dataUshort()  { _PR_setobj(0); }  // nil
    _objref_dataUshort(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_dataUshort();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_dataUshort(const _objref_dataUshort&);
    _objref_dataUshort& operator = (const _objref_dataUshort&);
    // not implemented

    friend class dataUshort;
  };

  class _pof_dataUshort : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_dataUshort() : _OMNI_NS(proxyObjectFactory)(dataUshort::_PD_repoId) {}
    virtual ~_pof_dataUshort();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_dataUshort :
    public virtual _impl_ProvidesPortStatisticsProvider,
    public virtual _impl_updateSRI
  {
  public:
    virtual ~_impl_dataUshort();

    virtual void pushPacket(const ::PortTypes::UshortSequence& data, const ::BULKIO::PrecisionUTCTime& T, ::CORBA::Boolean EOS, const char* streamID) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataUshort;

_CORBA_MODULE_END



_CORBA_MODULE POA_BULKIO
_CORBA_MODULE_BEG

  class dataUshort :
    public virtual BULKIO::_impl_dataUshort,
    public virtual ProvidesPortStatisticsProvider,
      public virtual updateSRI
  {
  public:
    virtual ~dataUshort();

    inline ::BULKIO::dataUshort_ptr _this() {
      return (::BULKIO::dataUshort_ptr) _do_this(::BULKIO::dataUshort::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_BULKIO
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, BULKIO::dataUshort_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::dataUshort_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::dataUshort_ptr& _s);



inline void
BULKIO::dataUshort::_marshalObjRef(::BULKIO::dataUshort_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataUshort
#endif

#endif  // __bio__dataUshort_hh__

