# DO NOT EDIT THIS FILE!
#
# Python module BULKIO generated by omniidl

import omniORB
omniORB.updateModule("sca.cf.BULKIO")

# ** 1. Stub files contributing to this module
import sca.cf.bio_dataFloat_idl

# ** 2. Sub-modules

# ** 3. End
