# DO NOT EDIT THIS FILE!
#
# Python module CF generated by omniidl

import omniORB
omniORB.updateModule("sca.cf.CF")

# ** 1. Stub files contributing to this module
import sca.cf.CFAdministratableInterface_idl
import sca.cf.CFCharSeq_idl
import sca.cf.CFDeviceAttributes_idl
import sca.cf.CFFileManager_idl
import sca.cf.CFLongLongSeq_idl
import sca.cf.CFProperties_idl
import sca.cf.CFULongLongSeq_idl
import sca.cf.CFAggregateDeviceAttributes_idl
import sca.cf.CFCommonTypes_idl
import sca.cf.CFDomainInstallation_idl
import sca.cf.CFFileSystem_idl
import sca.cf.CFLongSeq_idl
import sca.cf.CFPropertySet_idl
import sca.cf.CFULongSeq_idl
import sca.cf.CFAggregateDevice_idl
import sca.cf.CFComponentFactory_idl
import sca.cf.CFDomainManager_idl
import sca.cf.CFFloatSeq_idl
import sca.cf.CFOctetSeq_idl
import sca.cf.CFReleasableManager_idl
import sca.cf.CFUShortSeq_idl
import sca.cf.CFApplicationFactory_idl
import sca.cf.CFComponentIdentifier_idl
import sca.cf.CFDoubleSeq_idl
import sca.cf.CFFullComponentRegistry_idl
import sca.cf.CFPlatformTypes_idl
import sca.cf.CFShortSeq_idl
import sca.cf.CFApplicationManager_idl
import sca.cf.CFComponentRegistry_idl
import sca.cf.CFEventChannelRegistry_idl
import sca.cf.CFPortAccessor_idl
import sca.cf.CFSpecializedInfo_idl
import sca.cf.CFBooleanSeq_idl
import sca.cf.CFControllableInterface_idl
import sca.cf.CFExecutableInterface_idl
import sca.cf.CFLifeCycle_idl
import sca.cf.CFStringSeq_idl
import sca.cf.CFCapacityManagement_idl
import sca.cf.CFDeploymentAttributes_idl
import sca.cf.CFFile_idl
import sca.cf.CFLoadableInterface_idl
import sca.cf.CFPrimitiveTypes_idl
import sca.cf.CFTestableInterface_idl
import sca.cf.DeviceComponent_idl
import sca.cf.UTCTime_idl
import sca.cf.AdditionalTypes_idl
import sca.cf.Port_idl
import sca.cf.AggregateDevices_idl
import sca.cf.Component_idl

# ** 2. Sub-modules

# ** 3. End
